# Common port to service mappings
PORT_TO_SERVICE = {
    20: "FTP-data",
    21: "FTP",
    22: "SSH",
    23: "Telnet",
    25: "SMTP",
    53: "DNS",
    67: "DHCP Server",
    68: "DHCP Client",
    69: "TFTP",
    80: "HTTP",
    88: "Kerberos",
    110: "POP3",
    119: "NNTP",
    123: "NTP",
    135: "RPC",
    137: "NetBIOS-ns",
    138: "NetBIOS-dgm",
    139: "NetBIOS-ssn",
    143: "IMAP",
    161: "SNMP",
    162: "SNMP Trap",
    389: "LDAP",
    443: "HTTPS",
    445: "SMB",
    464: "Kerberos",
    465: "SMTPS",
    514: "Syslog",
    587: "SMTP Submission",
    636: "LDAPS",
    993: "IMAPS",
    995: "POP3S",
    1080: "SOCKS",
    1433: "MSSQL",
    1434: "MSSQL Browser",
    1521: "Oracle DB",
    1723: "PPTP",
    2049: "NFS",
    3306: "MySQL",
    3389: "RDP",
    5060: "SIP",
    5061: "SIPS",
    5432: "PostgreSQL",
    5900: "VNC",
    6379: "Redis",
    8000: "HTTP Alt",
    8080: "HTTP Proxy",
    8443: "HTTPS Alt",
    8888: "HTTP Alt",
    9000: "Jenkins",
    9090: "HTTP Alt",
    9200: "Elasticsearch",
    9300: "Elasticsearch",
    27017: "MongoDB",
}

# Banner patterns for service identification
BANNER_PATTERNS = {
    r"SSH-\d\.\d": "SSH",
    r"^220.*FTP": "FTP",
    r"^220.*SMTP": "SMTP",
    r"^HTTP\/\d\.\d \d{3}": "HTTP",
    r"^HTTP": "HTTP",
    r"^220.*ESMTP": "SMTP",
    r"^\+OK.*POP3": "POP3",
    r"^\* OK.*IMAP": "IMAP",
    r"^220.*SNMP": "SNMP",
    r"^VNC": "VNC",
    r"^\<\?xml": "XML Service",
    r"^RFB \d{3}\.\d{3}": "VNC",
    r"^SSH": "SSH",
    r"^WebSocket": "WebSocket",
    r"MySQL": "MySQL",
    r"MariaDB": "MariaDB",
    r"PostgreSQL": "PostgreSQL",
    r"Redis": "Redis",
    r"MongoDB": "MongoDB",
    r"^\xff\xfd": "Telnet",
    r"^MIIQn": "SSL/TLS",
    r"^AMQP": "AMQP",
    r"^Kafka": "Kafka",
    r"MSSQL": "MSSQL",
    r"Oracle Database": "Oracle",
    r"^LDAP": "LDAP",
    r"Elasticsearch": "Elasticsearch"
}
